### ISSUE TITLE
MemoryError: Error allocating 147865600 bytes of device memory (out of memory)

### ISSUE THREAD

**Issue by great-thoughts** [benanne/kaggle-ndsb#3]
Hi,
I am trying to run python train_convnet.py convroll4. However, I am getting this error:
Load data
Train model
Chunk 1/840
  setting learning rate to 0.0030000
  load training data onto GPU
  batch SGD
Error allocating 147865600 bytes of device memory (out of memory). Driver report 141447168 bytes free and 2147024896 bytes total 
Traceback (most recent call last):
  File "train_convnet.py", line 192, in <module>
    loss = iter_train(b)
  File "/Users/mas/PycharmProjects/kaggle-ndsb/env5/lib/python2.7/site-packages/theano/compile/function_module.py", line 606, in **call**
    storage_map=self.fn.storage_map)
  File "/Users/mas/PycharmProjects/kaggle-ndsb/env5/lib/python2.7/site-packages/theano/compile/function_module.py", line 595, in **call**
    outputs = self.fn()
MemoryError: Error allocating 147865600 bytes of device memory (out of memory).
Apply node that caused the error: GpuElemwise{add,no_inplace}(GpuDnnConv{workmem='small', inplace=True}.0, GpuDimShuffle{x,0,x,x}.0)
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, (True, False, True, True))]
Inputs shapes: [(128, 32, 95, 95), (1, 32, 1, 1)]
Inputs strides: [(288800, 9025, 95, 1), (0, 1, 0, 0)]
Inputs values: ['not shown', 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

I am using a mac book pro with NVIDIA GeForce GT 750M 2048 MB. 

Any help will be appreciated.

**Comment by benanne** [comment]
As described in the documentation (doc.pdf), at least 4GB of GPU memory is required for training most of the models. So unfortunately there is no easy fix for this error beyond investing in a better GPU. Sorry!
